package http.fri_uni_lj_si.prpo.SysMobPay.storitve.sprejemanjeNarocil;

import java.rmi.RemoteException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-17T16:44:17.363+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil", name = "SysMobPayPort")
@XmlSeeAlso({si.uni_lj.fri.prpo.SysMobPay.sporocila.ObjectFactory.class, ObjectFactory.class, si.uni_lj.fri.prpo.SysMobPay.tipi.ObjectFactory.class})
public interface SysMobPayPort {

    @WebMethod(operationName = "SprejmiNarocila", action = "http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil/SprejmiNarocila")
    @RequestWrapper(localName = "SprejmiNarocila", targetNamespace = "http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil", className = "http.fri_uni_lj_si.prpo.sysmobpay.storitve.sprejemanjenarocil.SprejmiNarocila")
    @ResponseWrapper(localName = "SprejmiNarocilaResponse", targetNamespace = "http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil", className = "http.fri_uni_lj_si.prpo.sysmobpay.storitve.sprejemanjenarocil.SprejmiNarocilaResponse")
    @WebResult(name = "output", targetNamespace = "")
    public si.uni_lj.fri.prpo.SysMobPay.sporocila.SysMobPayOdgovorSporocilo sprejmiNarocila(
        @WebParam(name = "input", targetNamespace = "")
        si.uni_lj.fri.prpo.SysMobPay.sporocila.SysMobPaySporocilo input
    ) throws RemoteException;
}
