package http.fri_uni_lj_si.prpo.SysMobPay.storitve.sprejemanjeNarocil;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-17T16:44:17.473+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "SysMobPay", 
                  wsdlLocation = "file:/C:/Users/Administrator/workspace/SysMobPayWS/WebContent/wsdl/SysMobPay.wsdl",
                  targetNamespace = "http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil") 
public class SysMobPay extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil", "SysMobPay");
    public final static QName SysMobPaySOAP = new QName("http://http://fri.uni-lj.si/prpo/SysMobPay/storitve/sprejemanjeNarocil", "SysMobPaySOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Administrator/workspace/SysMobPayWS/WebContent/wsdl/SysMobPay.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SysMobPay.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Administrator/workspace/SysMobPayWS/WebContent/wsdl/SysMobPay.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SysMobPay(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SysMobPay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SysMobPay() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysMobPay(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysMobPay(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SysMobPay(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SysMobPayPort
     */
    @WebEndpoint(name = "SysMobPaySOAP")
    public SysMobPayPort getSysMobPaySOAP() {
        return super.getPort(SysMobPaySOAP, SysMobPayPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SysMobPayPort
     */
    @WebEndpoint(name = "SysMobPaySOAP")
    public SysMobPayPort getSysMobPaySOAP(WebServiceFeature... features) {
        return super.getPort(SysMobPaySOAP, SysMobPayPort.class, features);
    }

}
